apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-fullstack-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-fullstack-app
  template:
    metadata:
      labels:
        app: gitops-fullstack-app
    spec:
      containers:
        - name: gitops-fullstack-app
          image: kuzyoyaroslav/gitops-fullstack-app:7d2c2fa2e70a2728616ee34d034b34325c18eaaf
          ports:
            - containerPort: 3001
