apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-fullstack-app-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-fullstack-app-ui
  template:
    metadata:
      labels:
        app: gitops-fullstack-app-ui
    spec:
      containers:
        - name: gitops-fullstack-app-ui
          image: kuzyoyaroslav/gitops-fullstack-app-ui:43f32e6b346bf8083dd2e4cdc6df33c927ced9f9
          ports:
            - containerPort: 3000
