apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-fullstack-app-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-fullstack-app-ui
  template:
    metadata:
      labels:
        app: gitops-fullstack-app-ui
    spec:
      containers:
        - name: gitops-fullstack-app-ui
          image: kuzyoyaroslav/gitops-fullstack-app-ui:b66758f3136c4aa7c0c103a4eafb6f89144df8ce
          ports:
            - containerPort: 3000
