replicas: 1

image:
  repository: kuzyoyaroslav/gitops-fullstack-app-ui
  tag: latest

service:
  port: 3000
  type: NodePort

imagePullSecrets:
  - name: regcred

ingress:
  enabled: true
  host: ui.local
  className: nginx
