apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-fullstack-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuzyo/gitops-k8-config.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-fullstack-app-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
