apiVersion: v1
kind: Service
metadata:
  name: gitops-fullstack-app-ui-service
spec:
  selector:
    app: gitops-fullstack-app-ui
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
